apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sonarqube-logs
  name: sonarqube-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
