library identifier: 'rt-ci-common@master',
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            remote: 'https://github.com/m0rv4i/RT-Jenkins-Piplines-Common.git'
        ]
    )


pipeline {

    agent {
        label 'Windows'
    }

    post {
        success {
            updateGitlabCommitStatus name: 'build', state: 'success'
            slackNotifyDeployed()
        }
        failure {
            updateGitlabCommitStatus name: 'build', state: 'failed'
            slackNotifyPipelineFailed()
        }
        cleanup {
            cleanup()
        }
    }

    options {
        timestamps()

        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All', secretToken: "c5db392d34e4dae4d1a34ccdb9232512") // TODO don't store here
    }

    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
        string name: 'projectId', defaultValue: 'No Project', description: 'projectId associated with the build.', trim: true
    }

    stages {

        stage('code quality') {
            steps {
                runMsbuildWithSonar("Release", "Any CPU", "4.5.1")
            }
        }

        stage('prep') {
            steps {
                //replaceAll("*.cs", "Mimikatz", "PROJECT")

                replaceSymbols()
            }
        }

        stage('build') {
            steps {
                runMsbuild("Release", "Any CPU", "4.5.1")
            }
        }

        stage('obfuscation') {
            steps {
                obfuscateDotnetBinary("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('opsec tests') {
            steps {
                testOpsec("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('scan') {
            steps {
                offlineVirusScan("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('deploy') {
            steps{
                script{
                    def uploadPattern = "${JOB_NAME}/bin/Release/*.exe"
                    def targetRepo = "engagements/${params.projectId}/${JOB_NAME}/"
                    def props = "language=csharp;ext=exe;type=internal;stage=postex"

                    deployToRtArtifactory(uploadPattern, targetRepo)
                }
            }
        }

    }

}
