library identifier: 'rt-ci-common@master',
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            remote: 'https://github.com/m0rv4i/RT-Jenkins-Piplines-Common.git'
        ]
    )

pipeline {

    agent {
        label 'Windows'
    }

    post {
        success {
            updateGitlabCommitStatus name: 'build', state: 'success'
            slackNotifyDeployed()
        }
        failure {
            updateGitlabCommitStatus name: 'build', state: 'failed'
            slackNotifyPipelineFailed()
        }
        cleanup {
            cleanup()
        }
    }

    options {
        timestamps()

        buildDiscarder(logRotator(numToKeepStr: '5'))

        gitLabConnection('Gitlab')
    }

    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All', secretToken: "2dabed56c7a17eb1810afc804e0ec151") // TODO don't store here
    }

    parameters {
        string name: 'ProjectID', defaultValue: 'No Project', description: 'ProjectID associated with the build.', trim: true
    }

    stages {

        stage('test') {
            steps {
                bat "python -m pytest"
            }
        }

        stage('analyse') {
            steps {
                sonarOnDocker()
            }
        }

        stage('deploy') {
            steps{
                script {

                    zip zipFile: '${JOB_NAME}.zip'

                    def uploadPattern = "${JOB_NAME}.zip"
                    def targetRepo = "engagements/${params.ProjectID}/${JOB_NAME}/"
                    def props = "language=python;ext=zip;type=c2;"

                    deployToRtArtifactory(uploadPattern, targetRepo)
                }
            }
        }

    }

}
