FROM docker.bintray.io/jfrog/artifactory-oss:latest

ADD artifactory.config.import.xml /var/opt/jfrog/artifactory/etc/artifactory/artifactory.config.import.xml
ADD security.import.xml /var/opt/jfrog/artifactory/etc/artifactory/security.import.xml
