library identifier: 'rt-ci-common@master',
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            remote: 'https://github.com/m0rv4i/RT-Jenkins-Piplines-Common.git'
        ]
    )

def gitURL = "https://github.com/GhostPack/Seatbelt"
def commitHash = "debc7e15d94c706c9104f6a21b844f10a95ee515"; // 8th Nov, 2020

pipeline {

    agent {
        label 'Windows'
    }

    post {
        success {
            updateGitlabCommitStatus name: 'build', state: 'success'
            slackNotifyDeployed()
        }
        failure {
            updateGitlabCommitStatus name: 'build', state: 'failed'
            slackNotifyPipelineFailed()
        }
        cleanup {
            cleanup()
        }
    }

    options {
        timestamps()

        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All', secretToken: "fdcb93bd3b1c05c33b0ca196850d784c")
    }

    parameters {
        gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
        string name: 'projectId', defaultValue: 'No Project', description: 'Project ID associated with the build.', trim: true
    }

    stages {

        stage('checkout') {
            steps {
                cloneExternalRepo(gitURL, commitHash)
            }
        }

        stage('prep') {
            steps {
                //replaceAll("*.cs", "Mimikatz", "PROJECT")

                replaceSymbols()
            }
        }

        stage('build') {
            steps {
                runMsbuild()
            }
        }

        stage('obfuscation') {
            steps {
                obfuscateDotnetBinary("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('opsec tests') {
            steps {
                testOpsec("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('scan') {
            steps {
                offlineVirusScan("${JOB_NAME}/bin/Release/${JOB_NAME}.exe")
            }
        }

        stage('deploy') {
            steps{
                script{
                    def uploadPattern = "${JOB_NAME}/bin/Release/*.exe"
                    def targetRepo = "engagements/${params.projectId}/${JOB_NAME}/"
                    def props = "language=csharp;ext=exe;stage=postex;type=external"

                    deployToRtArtifactory(uploadPattern, targetRepo, props)
                }
            }
        }

    }

}
