library identifier: 'rt-ci-common@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/m0rv4i/RT-Jenkins-Piplines-Common.git']
)

pipeline {

    agent {
        label 'Windows'
    }

    post {
        failure {
            updateGitlabCommitStatus name: 'build', state: 'failed'
        }
        success {
            updateGitlabCommitStatus name: 'build', state: 'success'
        }
    }

    options {
        gitLabConnection('Gitlab')
    }

    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All', secretToken: "fdcb93bd3b1c05c33b0ca196850d784c") // TODO don't store here
    }

    stages {

        stage('build-and-analyse') {

            steps {
                msbuildWithSonar()
            }
        }

        stage('deploy') {

            steps{

                script {
                    def server = Artifactory.server "ARTIFACTORY"

                    String rtProject = ""

                    if(env.RT_PROJECT){
                        rtProject = env.RT_PROJECT
                    } else {
                        rtProject = "No Project"
                    }

                    def uploadSpec =
                        '''{
                                "files": [
                                    {
                                        "pattern": "${JOB_NAME}/bin/Release/*.exe",
                                        "target": "engagements/''' + rtProject + '''/${JOB_NAME}/"
                                    }
                                ]
                            }'''

                    def buildInfo = server.upload spec: uploadSpec

                    server.publishBuildInfo buildInfo
                }
            }

        }

    }

}
